### ISSUE TITLE
言語仕様を決定する

### ISSUE THREAD

**Issue by NeM-T** [pdf-jube-joba/formal-verification-type#1]
型付け規則と評価規則をかく

**Comment by NeM-T** [comment]
De Bruijnにはしなくていいですよ

**Comment by pdf-jube-joba** [comment]
了解です

**Comment by pdf-jube-joba** [comment]
言語仕様は書ききれていませんが、決めるにせよ順々にやった方がいいと思うので、それ用に issue を立てます。
そのため、この issue は閉じる形にしようと思います。
