### ISSUE TITLE
代入とかアルファ同値とかベータ同値とか

### ISSUE THREAD

**Issue by pdf-jube-joba** [pdf-jube-joba/formal-verification-type#4]
とりあえず parameter で定義しておいて型システム定義に入る？

**Comment by NeM-T** [comment]
De Buruijn化をやるつもりなら確かに代入はparameterにしておいたほうが楽かもしれないし、α同値はいらなくなるのでいいと思いますよ

**Comment by pdf-jube-joba** [comment]
プルしたので終わり
